### ISSUE TITLE
哥们你的 emoji 列表哪来的

### ISSUE THREAD

**Issue by alswl** [Aixtuz/Rime-Config#1]
https://github.com/Aixtuz/Rime-Config/blob/8b5626e794c933603f49e1f5e0f55719ff2beef3/luna_pinyin.emoji.dict.yaml 这里面包含了 unicode 9.0 的 emoji 以及拼音映射。请问这个是怎么搞出来的？

**Comment by Aixtuz** [comment]
README 中有注明来源：[scomper](https://medium.com/@scomper) 的文章: [「鼠鬚管」的调教笔记](https://medium.com/@scomper/%E9%BC%A0%E9%A0%88%E7%AE%A1-%E7%9A%84%E8%B0%83%E6%95%99%E7%AC%94%E8%AE%B0-3fdeb0e78814#.8d1na3s5q)。

**Comment by alswl** [comment]
感谢
